services:

  redis-local:
    image: redis:7.0.11-alpine3.18
    container_name: redis-local
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./src/main/resources/rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana:9.0.9
    volumes:
      - grafana_data:/grafana
    ports:
      - "3000:3000"

volumes:
  redis_data:
  grafana_data:
