global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

scrape_configs:
  - job_name: "users-job"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "service-api-user"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: "prom-lab"
          service: "service-prometheus"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]